### ISSUE TITLE
broadcastStdTx mode should be "sync" and not "block"

### ISSUE THREAD

**Issue by liberorignanese** [commercionetwork/commercio-sdk.kt#3]
In
https://github.com/commercionetwork/commercio-sdk.kt/blob/master/src/main/kotlin/network/commercio/sdk/tx/TxHelper.kt
mode should be "sync"

**Comment by Valentina-92** [comment]
The default value for mode is ''sync''.
This issue that has already been resolved in commit   [fix TxHelper](https://github.com/commercionetwork/commercio-sdk.kt/commit/6ad8ad026a5e9542ba64e4f9c16dd07012ad2dae#diff-9d0045769ce381cec8a25e9450cc4113830a61e5be438b59bff24cbc005f8fd5).
