### ISSUE TITLE
Add optional fee parameter to helper methods

### ISSUE THREAD

**Issue by zenit70** [commercionetwork/commercio-sdk.kt#6]
The class `DocsHelper` currently supports a custom list of fees only in the method `shareDocument()`.  Because the SDK is built to support different types of `StdCoin` also the other methods should take a `fee` parameter. For retro compatibility the new parameter should be optional with a default value.

List of methods that should be updated:

- [ ] `DocsHelper.sendDocumentReceipt()`
- [ ] `MembershipHelper.inviteUser()`
- [ ] `MembershipHelper.buyMembership()`
- [ ] `MintHelper.openCdp()`
      Note: the call to `MsgOpenCdp()` should also be updated with the custom fee list
- [ ] `MintHelper.closeCdp()`
- [ ] `IdHelper.setDidDocument()`
- [ ] `IdHelper.requestDidPowerUp()`
- [ ] `IdHelper.MsgRequestDidPowerUp()`

If you notice I've forgotten any helper functions, update those too.

The changes also needs to be reflected on the documentation and the examples.

**Comment by Valentina-92** [comment]
The last item on the list is IdHelper.requestDidDeposit (not IdHelper.MsgRequestDidPowerUp())

Updated the examples of the documentation in kotlin (commercio.developers.guide)
